services:
  web:
    image: php7-apache:latest
    container_name: php7-apache
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www/html
      - ./etc/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./etc/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
